### ISSUE TITLE
Add meta tags

### ISSUE THREAD

**Issue by bobbermac** [forgotten-roads/blog#29]
Google-search-friendly meta tags:

* [x] description

General:

* [x] author
* [x] generator

Dublin Core:

* [x] DC.coverage (year range)
* [x] DC.subject
* [ ] DC.keywords (not regular meta tag keywords)
* [x] DC.creator
* [x] DC.publisher
* [x] DC.date
* [x] DC.format
* [x] DC.type
* [x] DC.rights (creative commons license URL)
* [x] DC.identifier (post URL)
* [x] DCTERMS.audience
* [x] DCTERMS.abstract

Example:
```html
<head profile="http://dublincore.org/documents/dcq-html/">
<title>Expressing Dublin Core in HTML/XHTML meta and link elements</title>
<link rel="schema.DC" href="http://purl.org/dc/elements/1.1/" />
<link rel="schema.DCTERMS" href="http://purl.org/dc/terms/" />

<meta name="DC.title" lang="en" content="Expressing Dublin Core
in HTML/XHTML meta and link elements" />
<meta name="DC.creator" content="Andy Powell, UKOLN, University of Bath" />
<meta name="DCTERMS.issued" scheme="DCTERMS.W3CDTF" content="2003-11-01" />
<meta name="DC.identifier" scheme="DCTERMS.URI"
content="http://dublincore.org/documents/dcq-html/" />
<link rel="DCTERMS.replaces" hreflang="en"
href="http://dublincore.org/documents/2000/08/15/dcq-html/" />
<meta name="DCTERMS.abstract" content="This document describes how
qualified Dublin Core metadata can be encoded
in HTML/XHTML &lt;meta&gt; elements" />
<meta name="DC.format" scheme="DCTERMS.IMT" content="text/html" />
<meta name="DC.type" scheme="DCTERMS.DCMIType" content="Text" />
</head>
```
Open Graph (Facebook):

* [x] og.title
* [x] og:url
* [x] og:type (blog)
* [x] og:description
* [x] og:image (recommended 1200 pixels x 627)
* [x] og:site_name

![image](https://user-images.githubusercontent.com/24781520/27523733-cda0f708-59f4-11e7-9e12-4deaf9731be1.png)

Twitter:

* [x] twitter:card (maps to og:type) use `summary_large_image`
* [x] twitter:title
* [x] twitter:description
* [x] twitter:url
* [x] twitter:image
* [x] twitter:site
* [x] twitter:creator

```
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@nytimes">
<meta name="twitter:creator" content="@SarahMaslinNir">
<meta name="twitter:title" content="Parade of Fans for Houston’s Funeral">
<meta name="twitter:description" content="NEWARK - The guest list and parade of limousines with celebrities emerging from them seemed more suited to a red carpet event in Hollywood or New York than than a gritty stretch of Sussex Avenue near the former site of the James M. Baxter Terrace public housing project here.">
<meta name="twitter:image" content="http://graphics8.nytimes.com/images/2012/02/19/us/19whitney-span/19whitney-span-articleLarge.jpg">
```
See:
 * https://support.google.com/webmasters/answer/79812?hl=en
 * https://www.w3.org/TR/html5/document-metadata.html#the-meta-element
 * http://dublincore.org/documents/dc-html/
 * http://dublincore.org/documents/dcq-html/
 * http://dublincore.org/documents/2001/04/12/usageguide/generic.shtml
 * https://blog.kissmetrics.com/open-graph-meta-tags/
 * https://dev.twitter.com/cards/types/summary-large-image

**Comment by bobbermac** [comment]
Done.
